name: lint

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/amezin/gnome-shell-pod-34:master

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: npm install eslint
    - run: npx eslint .

  glib-compile-schemas:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/amezin/gnome-shell-pod-34:master

    steps:
    - uses: actions/checkout@v2
    - run: make schemas/gschemas.compiled

  gtk-builder-validate:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/amezin/gnome-shell-pod-34:master

    steps:
    - uses: actions/checkout@v2
    - run: xvfb-run make gtk-builder-validate
