name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        fedora-version:
          - '32'
          - '33'
          - '34'
          - '35'
        session:
          - 'gnome-xsession'
          - 'gnome-wayland-nested'
          - 'gnome-wayland-nested-highdpi'
          - 'gnome-wayland-nested-dual-monitor'
        exclude:
          - fedora-version: '33'
            session: 'gnome-wayland-nested-dual-monitor'
    env:
      IMAGE: ghcr.io/amezin/gnome-shell-pod-${{ matrix.fedora-version }}:master
      PY_COLORS: 1
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: sudo apt-get install -y python3-gi python3-wand tox
    - run: npm ci
    - run: sudo podman pull "${{ env.IMAGE }}"
    - run: sudo podman run --rm -i -v "${PWD}:${PWD}" -w "${PWD}" "${{ env.IMAGE }}" xvfb-run make test-deps
    - run: tox -vv --notest --sitepackages
      working-directory: test
    - run: tox --sitepackages -- --podman sudo podman --container-image "${{ env.IMAGE }}" --gnome-session "${{ matrix.session }}" --color=yes -n 2
      working-directory: test
    - uses: actions/upload-artifact@v2
      with:
        name: test-${{ matrix.fedora-version }}-${{ matrix.session }}
        path: |
          test/report.html
          test/junit.xml
          test/assets
      if: always()
