name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        fedora-version:
          - '32'
          - '33'
          - '34'
          - '35'
        session:
          - 'gnome-xsession'
          - 'gnome-wayland-nested'
          - 'gnome-wayland-nested-highdpi'
          - 'gnome-wayland-nested-dual-monitor'
        exclude:
          - fedora-version: '33'
            session: 'gnome-wayland-nested-dual-monitor'
    env:
      IMAGE: ghcr.io/amezin/gnome-shell-pod-${{ matrix.fedora-version }}:master
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: npm ci
    - run: sudo podman pull "${{ env.IMAGE }}"
    - run: sudo podman run --rm -i -v "${PWD}:${PWD}" -w "${PWD}" "${{ env.IMAGE }}" xvfb-run make test-deps
    - run: sudo ./run_test_podman.sh -i "${{ env.IMAGE }}" -s "${{ matrix.session }}"
      working-directory: test
    - uses: actions/upload-artifact@v2
      with:
        name: test-${{ matrix.fedora-version }}-${{ matrix.session }}
        path: |
          test/Xvfb_screen*.png
          test/journal.txt
      if: always()
